spring:
  application.name: @project.artifactId@
  banner.location: banner.txt
  main:
    web-application-type: reactive
  jackson:
    serialization:
      indent-output: on
  session:
    timeout: 36000  # in seconds; Goal: same lifetime like SSO Session (e.g. 10 hours)

server:
  port: 8082
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false

management:
  endpoints:
    enabled-by-default: false
    web:
      cors:
        allowedOrigins:
          - "http://localhost:8081"
          - "http://127.0.0.1:8081"
        allowedMethods: "*"
        allowedHeaders: "*"
        allowCredentials: on
        maxAge: 3600
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: on
    info:
      enabled: on
info.application.name: ${spring.application.name}
info.application.version: @project.version@

---
spring:
  profiles: no-security
  cloud:
    gateway:
      default-filters:
        - RemoveResponseHeader=Expires

  realm: intrap

  # Security config for profile no-security.
  # Necessary because the issuer-uri is called independently from the choosen profile.
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://ssotest.muenchen.de/auth/realms/${spring.realm}
              # Registration Config required to start service, even if not used
        registration:
          keycloak:
            client-id: vuedemo
            client-secret: <todo>
